name: crypthora_chat_wrapper
description: "Wrapper for CrypthoraChat"
publish_to: 'none'

version: 0.0.1-alpha.9+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_foreground_task: ^9.1.0
  web_socket_channel: ^3.0.3
  flutter_local_notifications: ^19.4.1
  shared_preferences: ^2.5.3
  flutter_inappwebview: ^6.1.5
  permission_handler: ^12.0.1
  flutter_i18n: ^0.36.3
  http: ^1.5.0
  connectivity_plus: ^7.0.0
  package_info_plus: ^9.0.0
  url_launcher: ^6.3.2
  unifiedpush: ^6.2.0
  workmanager: ^0.9.0+3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/i18n/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 24
  adaptive_icon_background: "#423380"
  adaptive_icon_foreground: "assets/icon/icon.png"
  adaptive_icon_monochrome: "assets/icon/icon.png"